[project]
name = "mytinytransformer"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "pyyaml>=6.0.3",
    "tqdm>=4.70.0",
]

[project.optional-dependencies]
cu130 = ["torch>=2.13.0"]
cu126 = ["torch>=2.13.0"]

[tool.uv]
conflicts = [
    [ { extra = "cu130" }, { extra = "cu126" } ],
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", extra = "cu130" },
    { index = "pytorch-cu126", extra = "cu126" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

# To use CUDA 13.0:
# uv sync --extra cu130
#
# If CUDA 13.0 does not work:
# uv sync --extra cu126