[project]
name = "mytinytransformer"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "pyyaml>=6.0.3",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
]

[project.optional-dependencies]
cu126 = []

[tool.uv.sources]
torch = [
    { index = "pytorch-cu126", marker = "extra == 'cu126'" },
    { index = "pytorch-cu130", marker = "extra != 'cu126'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

# If CUDA 13.0 does not work,
# uv sync --extra cu126
# or
# uv sync --extra cu126 --reinstall-package torch